[project]
name = "diamonds-ml-app"
version = "0.1.0"
description = "Interactive Streamlit dashboard and ML price predictor for diamonds"
authors = [
    {name = "ari.ira17-mcb",email = "ari.ira17@yandex.ru"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "streamlit (>=1.57.0,<2.0.0)",
    "pandas (>=3.0.2,<4.0.0)",
    "watchdog (>=6.0.0,<7.0.0)",
    "seaborn (>=0.13.2,<0.14.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
